[config]
context = "java"

[[templates]]
name = "nal, newArrayList"
description = "init (array) list"
pattern = """
${:import(java.util.ArrayList)}\
new ArrayList<>();"""

[[templates]]
name = "nhs, newHashSet"
description = "init (hash) set"
pattern = """
${:import(java.util.HashSet)}\
new HashSet<>();"""


[[templates]]
name = "nhm, newHashMap"
description = "init (hash) map"
pattern = """
${:import(java.util.HashMap)}\
new HashMap<>();"""

[[templates]]
name = "al, list, asList"
description = "create a list"
pattern = """
${:importStatic(java.util.Arrays.asList)}\
asList(${values});"""
