[config]
context = "java"

[[templates]]
name = "nested"
description = "nested test"
pattern = """
${:import(org.junit.jupiter.api.Nested)}\
@Nested
class ${NestedTestName} {

	${cursor}

}"""

[[templates]]
name = "test"
description = "test"
pattern = """
${:import(org.junit.jupiter.api.Test)}\
@Test${cursor}"""

[[templates]]
name = "tm"
description = "test method"
pattern = """
${:import(org.junit.jupiter.api.Test)}\
@Test
void ${TestName}() {
	${cursor}
}"""

[[templates]]
name = "pt"
description = "parameterized test"
pattern = """
${:import(org.junit.jupiter.params.ParameterizedTest)}\
@ParameterizedTest${cursor}"""

[[templates]]
name = "ptm"
description = "parameterized test method"
pattern = """
${:import(org.junit.jupiter.params.ParameterizedTest)}\
@ParameterizedTest
${Parameters}
void ${TestName}(${Arguments}) {
	${cursor}
}"""

[[templates]]
name = "pcsv, csvSource"
description = "CSV-source for a parameterized test"
pattern = """
${:import(org.junit.jupiter.params.provider.CsvSource)}\
@CsvSource({ //
	${value}, //${cursor}
})"""

[[templates]]
name = "pval, valueSource"
description = "value-source for a parameterized test"
pattern = """
${:import(org.junit.jupiter.params.provider.ValueSource)}\
@ValueSource(${valueType} = {${values}})"""
